{% set name = "poetry-conda" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry_conda-{{ version }}.tar.gz
  sha256: b26e92e8d0af7510c36f99f0f3fafc982c8cd2b0eb7063e113b918afe7942fdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - poetry >=1.5.0,<3

test:
  imports:
    - poetry_conda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/renan-r-santos/poetry-conda
  summary: Poetry plugin that allows for the creation of virtual environments using Poetry, without interfering with the Conda environment in which Poetry is installed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - renan-r-santos
