{% set name = "poetry-conda" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry_conda-{{ version }}.tar.gz
  sha256: e1443541b63c81c28a40fff50b8b9c590699b4453315ddf970bd9d839499be9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - poetry >=1.3.0,<2

test:
  imports:
    - poetry_conda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/renan-r-santos/poetry-conda
  summary: Poetry plugin that allows for the creation of virtual environments using Poetry, without interfering with the Conda environment in which Poetry is installed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - renan-r-santos
